version: "3.5"

services:

  openfibre-cove-app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      DEBUG: "True"
      ALLOWED_HOSTS: "localhost"
    volumes:
      - ".:/app"
