version: "3.5"

services:

  openfibre-cove-app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      DEBUG: "True"
      ALLOWED_HOSTS: "localhost"
      CELERY_BROKER_URL: "redis://openfibre-cove-redis-dev:6379/0"
    volumes:
      - ".:/app"
    command: "/bin/bash -c \"/etc/init.d/nginx start && gunicorn --bind 0.0.0.0:8000 cove_project.wsgi:application\""
    depends_on:
      - openfibre-cove-redis-dev

  openfibre-cove-worker-dev:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DEBUG: "True"
      CELERY_BROKER_URL: "redis://openfibre-cove-redis-dev:6379/0"
    volumes:
      - ".:/app"
    command: "celery -A libcoveweb2.celery worker -l info -c 1"
    depends_on:
      - openfibre-cove-redis-dev

  openfibre-cove-redis-dev:
    image: redis:7

networks:
  default:
    name: openfibre-cove-dev
