# Generated by Django 3.2.16 on 2022-11-01 12:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SuppliedData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("format", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SuppliedDataFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.TextField()),
                ("size", models.PositiveBigIntegerField()),
                ("content_type", models.TextField(null=True)),
                ("charset", models.TextField(null=True)),
                (
                    "supplied_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libcoveweb2.supplieddata",
                    ),
                ),
            ],
        ),
    ]
