# Generated by Django 3.2.16 on 2022-11-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libcoveweb2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplieddatafile",
            name="meta",
            field=models.JSONField(null=True),
        ),
    ]
