# Generated by Django 3.2.16 on 2023-03-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libcoveweb2", "0002_supplieddatafile_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplieddata",
            name="expired",
            field=models.DateTimeField(null=True),
        ),
    ]
