# Generated by Django 3.2.16 on 2023-03-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libcoveweb2", "0003_supplieddata_expired"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplieddatafile",
            name="source_method",
            field=models.TextField(null=True),
        ),
    ]
