# Generated by Django 3.2.16 on 2023-03-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libcoveweb2", "0004_supplieddatafile_source_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplieddatafile",
            name="source_url",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="supplieddatafile",
            name="size",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
