# Generated by Django 3.2.16 on 2023-03-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libcoveweb2", "0005_url_uploads"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplieddata",
            name="processed",
            field=models.DateTimeField(null=True),
        ),
    ]
