# Generated by Django 3.2.16 on 2023-04-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libcoveweb2", "0006_supplieddata_processed"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplieddata",
            name="error",
            field=models.TextField(null=True),
        ),
    ]
