# Generated by Django 3.2.16 on 2023-04-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libcoveweb2", "0007_supplieddata_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplieddata",
            name="meta",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="supplieddatafile",
            name="meta",
            field=models.JSONField(default=dict),
        ),
    ]
