name: Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup python
      uses: actions/setup-python@v6
      with:
        # Match live server, version set in Dockerfile
        python-version: 3.11
        architecture: x64
    - run: pip install -r requirements_dev.txt
    - run: isort --check-only cove_project/ cove_ofds/
    - run: black --check cove_project/ cove_ofds/
    - run: flake8 cove_project/ cove_ofds/
