name: Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: x64
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_dev.txt') }}-${{ matrix.python-version }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - run: pip install -r requirements_dev.txt
    - run: isort --check-only cove_project/ cove_ofds/
    - run: black --check cove_project/ cove_ofds/
    - run: flake8 cove_project/ cove_ofds/
