name: Live Deploy
on: [push]

jobs:
  live-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/live'
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DOKKUSD_LIVE_SSH_PRIVATE_KEY }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.DOKKUSD_LIVE_SSH_KEYSCAN }}
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: x64
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}-${{ matrix.python-version }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - run: pip install dokkusd
    - run: python -m dokkusd.cli deploy --appname ${{ secrets.DOKKUSD_LIVE_APP_NAME }}
      env:
        DOKKUSD_REMOTE_HOST: ${{ secrets.DOKKUSD_LIVE_REMOTE_HOST }}
        DOKKUSD_REMOTE_PORT: ${{ secrets.DOKKUSD_LIVE_REMOTE_PORT }}
        DOKKUSD_REMOTE_USER: ${{ secrets.DOKKUSD_LIVE_REMOTE_USER }}
        DOKKUSD_LETS_ENCRYPT: ${{ secrets.DOKKUSD_LIVE_LETS_ENCRYPT }}
        DOKKUSD_ENVIRONMENT_VARIABLES_JSON: ${{ secrets.DOKKUSD_LIVE_ENVIRONMENT_VARIABLES_JSON }}
